### ISSUE TITLE
subtests don't seem to work with --last-failed

### ISSUE THREAD

**Issue by exhuma** [pytest-dev/pytest-subtests#14] opened 2019-04-16 07:58 UTC
I usually run my tests with `--lf` and have just now added subtests.

Failed subtests don't seem to be registered as "last failed". This causes all tests to be rerun even if some subtests failed.

**Comment by exhuma** [comment] 2019-04-16 08:03
I have now added a workaround by simply counting the "passes":

    expected_words = ["primary", "port", "scope", "port", "poll_ip", "name"]
        num_passed = 0
        for word in expected_words:
            with subtests.test(word=word):
                assert word in response_text
                num_passed += 1
        # this is a workaroud for subtests not being recorded as failures
        # see https://github.com/pytest-dev/pytest-subtests/issues/14
        assert num_passed == len(expected_words)

**Comment by nicoddemus** [comment] 2019-04-25 22:00
Hi @exhuma,

It seems to work for me:

```python
def test(subtests):
    response_text = "primary port scope "
    expected_words = ["primary", "port", "scope", "port", "poll_ip", "name"]
    for word in expected_words:
        with subtests.test(word=word):
            assert word in response_text
```

First time:

```
λ pytest .tmp\test.py -q --tb=short
....FF..                                                       [100%]
============================= FAILURES ==============================
_______________________ test (word='poll_ip') _______________________
.tmp\test.py:7: in test
    assert word in response_text
E   AssertionError: assert 'poll_ip' in 'primary port scope '
________________________ test (word='name') _________________________
.tmp\test.py:7: in test
    assert word in response_text
E   AssertionError: assert 'name' in 'primary port scope '
2 failed, 2 passed in 0.04 seconds
```

Second time with `--lf`:

```
λ pytest .tmp\test.py -q --tb=short --lf
....FF..                                                       [100%]
============================= FAILURES ==============================
_______________________ test (word='poll_ip') _______________________
.tmp\test.py:7: in test
    assert word in response_text
E   AssertionError: assert 'poll_ip' in 'primary port scope '
________________________ test (word='name') _________________________
.tmp\test.py:7: in test
    assert word in response_text
E   AssertionError: assert 'name' in 'primary port scope '
2 failed, 2 passed in 0.15 seconds
```

So `--lf` executed the previously failed `test` function. 

Can you provide a reproducible example and explain what you were expecting?

Thanks!

**Comment by chingc** [comment] 2021-12-13 23:38
@nicoddemus I'm experiencing the same issue.  Here is my test:

```
def test_fails(subtests):
    for i in range(0, 2):
        with subtests.test(msg="error", i=i):
            assert i == 1

def test_passes():
    assert True
```

## Result with `pytest -q`

The output from this is what I expected.

```
============================ FAILURES ============================
____________________ test_fails [error] (i=0) ____________________

    def test_fails(subtests):
        for i in range(0, 2):
            with subtests.test(msg="error", i=i):
>               assert i == 1
E               assert 0 == 1

test_subtest.py:4: AssertionError
==================== short test summary info =====================
FAILED test_subtest.py::test_fails - assert 0 == 1
1 failed, 2 passed, 2 warnings in 0.21s
```

## Result with `pytest -q --lf`

It's re-running all tests including `test_passes` which didn't fail.  This is not what I expected.

```
============================ FAILURES ============================
____________________ test_fails [error] (i=0) ____________________

    def test_fails(subtests):
        for i in range(0, 2):
            with subtests.test(msg="error", i=i):
>               assert i == 1
E               assert 0 == 1

test_subtest.py:4: AssertionError
==================== short test summary info =====================
FAILED test_subtest.py::test_fails - assert 0 == 1
1 failed, 2 passed, 2 warnings in 0.25s
```

## Result with `pytest -q --lf --lfnf=none`

This is the worst case because I know something failed and it didn't re-run anything!

```
2 deselected in 0.01s
```

**Comment by nicoddemus** [comment] 2021-12-14 10:40
Hi @chingc,

Indeed seems to be a problem, however this is a different problem than the one reported on this thread, would you mind open a new one? Thanks!

I'm closing this one as a reproducer was not provided for the original issue.

**Closed by nicoddemus** 2021-12-14 10:40 UTC
