### ISSUE TITLE
No logs?

### ISSUE THREAD

**Issue by tzachshabtay** [pytest-dev/pytest-subtests#18] opened 2019-07-29 20:43 UTC
Thanks for the plugin, subtests are properly named now. However...

After installing the plugin the whole section in the output showing the logs is gone (i.e the `"Captured stdout call"` and `"Captured log call"` that appear in the bottom without this plugin).

It's very hard to debug failing tests without logs, making this plugin currently unusable for me.

**Comment by nicoddemus** [comment] 2019-07-31 12:45
Hi @tzachshabtay,

Thanks for the report, that's clearly a bug.

**Comment by icemac** [comment] 2020-01-16 15:58
Are there any news on this issue?

I like this plug-in and started using it in a project. My current trick to see the test output of the failures is to run the tests with `-s`. This helps but does not seem to be a long term solution.

**Comment by nicoddemus** [comment] 2020-01-16 16:00
Hi @icemac thanks for the ping!

I apologize, I have not allocated time to work on this plugin lately because of more important stuff happening in pytest/xdist/etc.

This plugin is not abandoned though, I will try harder to allocate more time for it in the next days. 👍

**Comment by nicoddemus** [comment] 2020-01-23 00:03
`0.3.0` has been released with this fix. 🎉

**Closed** 2020-01-23 00:02 UTC
Labels: bug

**Comment by r-or** [comment] 2020-05-29 02:16
Hi, 
for me this issue is still there.
```sh
└─ $ ▶ pip freeze | grep subtest
pytest-subtests==0.3.1
```
Without subtests installed it works just fine :)

**Comment by nicoddemus** [comment] 2020-06-02 15:11
Hi @r-or,

Can you show a test which reproduces the issue? Thanks!

**Comment by nicoddemus** [comment] 2020-06-10 23:45
Thanks, created #26 as follow up, now the issue is clear! Sorry about the delay.

> but why do I get 2 failed and 1 passed in the above instead of just 2 failures?

Because the test containing the subtests passed. This is to differentiate from the case where it also fails after the `subTest` call:

```python
class PytestSubtestTest(unittest.TestCase):
    def test_subtest_stdout(self):
        for i in range(2):
            with self.subTest(i=i):
                print(f"{i}: Print something to stdout")
                self.assertEqual(0, 1)
        assert 0, "test failed" 
```

This will get you 3 failures: 2 from the subtests, and one from the failing `assert` after the `subTest` context-manager.
