### ISSUE TITLE
Unclear test failure reporting

### ISSUE THREAD

**Issue by Conchylicultor** [pytest-dev/pytest-subtests#72] opened 2022-06-09 13:09 UTC
Currently when many substests are failing, the output looks like:

```
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-6.2.3, py-1.10.0, pluggy-0.9.0 -- None
cachedir: ...
rootdir: ...
collecting ... collected 72 items

dtypes_test.py::test_dtype[np-item0] PASSED                              [  1%]
dtypes_test.py::test_dtype[np-item0] FAILED                              [  1%]
dtypes_test.py::test_dtype[np-item0] FAILED                              [  1%]
dtypes_test.py::test_dtype[np-item0] FAILED                              [  1%]
...
```

It makes it hard to understand which subtests pass or not. It would be nice if the subtest name was displayed, like:

```
dtypes_test.py::test_dtype[np-item0] [np.int32] PASSED                              [  1%]
dtypes_test.py::test_dtype[np-item0] [np.int64] FAILED                              [  1%]
dtypes_test.py::test_dtype[np-item0] [np.float32] FAILED                              [  1%]
dtypes_test.py::test_dtype[np-item0] [np.float64] FAILED                              [  1%]
...
```

**Comment by RonnyPfannschmidt** [comment] 2022-06-09 13:47
please provide a minimal reproducer for the test ids, i believe messages are added when possible

**Comment by Conchylicultor** [comment] 2022-06-09 14:08
For example the official example:

```
def test_abc(subtests):

    for i in range(5):
        with subtests.test(i=i):
            assert i % 2 == 0
```

Display:

```
============================= test session starts ==============================
platform darwin -- Python 3.10.0, pytest-7.1.2, pluggy-1.0.0 -- /Users/epot/.pyenv/versions/3.10.0/bin/python
cachedir: .pytest_cache
rootdir: /Users/epot/__A__/Code/pytypedoc
plugins: xdist-2.5.0, anyio-3.5.0, forked-1.4.0, subtests-0.8.0
collecting ... collected 1 item

experiments/test_issue_test.py::test_abc SUBPASS                         [100%]
experiments/test_issue_test.py::test_abc SUBFAIL                         [100%]
experiments/test_issue_test.py::test_abc SUBPASS                         [100%]
experiments/test_issue_test.py::test_abc SUBFAIL                         [100%]
experiments/test_issue_test.py::test_abc SUBPASS                         [100%]
experiments/test_issue_test.py::test_abc PASSED                          [100%]

=========================== short test summary info ============================
SUBFAIL experiments/test_issue_test.py::test_abc - assert (1 % 2) == 0
SUBFAIL experiments/test_issue_test.py::test_abc - assert (3 % 2) == 0
```

There is no indication of which subtest has failed in the name: `test_abc (i=3)`. I would have expected something like:
```
experiments/test_issue_test.py::test_abc (i=0) SUBPASS                         [100%]
experiments/test_issue_test.py::test_abc (i=1) SUBFAIL                         [100%]
```

**Comment by RonnyPfannschmidt** [comment] 2022-06-09 15:36
i see what you mean, currently only the msg is passed over for display

**Comment by Conchylicultor** [comment] 2022-06-12 09:12
> i see what you mean, currently only the msg is passed over for display

I'm not sure what you mean, replacing `subtests.test(i=i)` by `subtests.test(f'msg{i}')` do not work either.

**Comment by mauvilsa** [comment] 2023-05-02 10:02
This seems to be a duplicate of #6. The missing subtest details are even in the unit tests:

https://github.com/pytest-dev/pytest-subtests/blob/0e6e328dc77a182ac5d076d0908468371afaade1/tests/test_subtests.py#L46-L51

**Comment by nicoddemus** [comment] 2023-05-03 13:32
Closing as duplicate of #6. :+1:

**Closed** 2023-05-03 13:33 UTC
Labels: enhancement
